# Generated by Django 2.2 on 2021-06-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
        ('snack_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snack',
            name='disliked_by',
            field=models.ManyToManyField(related_name='disliked_snacks', to='login_app.User'),
        ),
        migrations.AddField(
            model_name='snack',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_snacks', to='login_app.User'),
        ),
    ]
